### ISSUE TITLE
Request for release

### ISSUE THREAD

**Issue by bascan** [datacleaner/metamodel#8]
Hi data cleaners,

Thanks for merging https://github.com/datacleaner/metamodel/pull/7!
We'd like to stay with your fork and fix our CVEs.
Do you currently have any release planned?

Many thanks in advance :-)

**Comment by kaspersorensen** [comment]
Hi @bascan
Yes, let's get this released! I will start the process soon.

**Comment by kaspersorensen** [comment]
Version 5.3.6 has been released ([tag](https://github.com/datacleaner/metamodel/releases/tag/MetaModel-5.3.6))
